/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import PERS.AssociadoPERS;
import PERS.EnderecoPERS;
import VO.AssociadoVO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class IUAssociados extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form Associados
     */
    public IUAssociados() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AssociadoPERS associadoPERS = new AssociadoPERS();     
        List associados = associadoPERS.retornarAssociados();
        
        model = (DefaultTableModel) tableAssociados.getModel(); 
        AssociadoVO associadoVO;
        int i;
        int tam = associados.size();
        for(i=0; i<tam; i++){
            associadoVO = (AssociadoVO) associados.get(i);       
            model.addRow(new String [] {associadoVO.getCodigo(),associadoVO.getNome(),associadoVO.getCPF(),associadoVO.getRG(), associadoVO.getTelefone(), associadoVO.getEmail()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAssociados = new javax.swing.JTable();
        alterar = new javax.swing.JButton();
        exluir = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        endereco = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Associados");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        tableAssociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAssociados);
        if (tableAssociados.getColumnModel().getColumnCount() > 0) {
            tableAssociados.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableAssociados.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableAssociados.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableAssociados.getColumnModel().getColumn(3).setPreferredWidth(10);
            tableAssociados.getColumnModel().getColumn(4).setPreferredWidth(10);
            tableAssociados.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        exluir.setText("Excluir");
        exluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exluirActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        endereco.setText("Endereço");
        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(exluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterar)
                    .addComponent(exluir)
                    .addComponent(cadastrar)
                    .addComponent(voltar)
                    .addComponent(endereco))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        this.dispose();
        new IUCadastrarAssociado().setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
        new IUMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        
        int linhaSelecionada = tableAssociados.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        String codigoAssociado = (String) model.getValueAt(linhaSelecionada, 0);
        
        this.dispose();
        new IUExibirEndereco(codigoAssociado).setVisible(true);
  
    }//GEN-LAST:event_enderecoActionPerformed

    private void exluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exluirActionPerformed
        int linhaSelecionada = tableAssociados.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        String codigoAssociado = (String) model.getValueAt(linhaSelecionada, 0);
        
        AssociadoPERS associadoPERS = new AssociadoPERS();
        String msg = associadoPERS.excluirAssociado(codigoAssociado);
        
        JOptionPane.showMessageDialog(null, msg);
        this.dispose();
        new IUAssociados().setVisible(true);
        
    }//GEN-LAST:event_exluirActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        int linhaSelecionada = tableAssociados.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        
        AssociadoVO associadoVO = new AssociadoVO();
        associadoVO.setCodigo((String) model.getValueAt(linhaSelecionada, 0));
        associadoVO.setNome((String) model.getValueAt(linhaSelecionada, 1));
        associadoVO.setCPF((String) model.getValueAt(linhaSelecionada, 2));
        associadoVO.setRG((String) model.getValueAt(linhaSelecionada, 3));
        associadoVO.setTelefone((String) model.getValueAt(linhaSelecionada, 4));
        associadoVO.setEmail((String) model.getValueAt(linhaSelecionada, 5));
        
        EnderecoPERS enderecoPERS = new EnderecoPERS();
        associadoVO.setEndereco(enderecoPERS.retornarEndereco(associadoVO.getCodigo()));
        
        this.dispose();
        new IUAlterarAssociado(associadoVO).setVisible(true);
        
    }//GEN-LAST:event_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUAssociados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUAssociados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUAssociados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUAssociados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUAssociados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton endereco;
    private javax.swing.JButton exluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAssociados;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
