/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import PERS.LivroPERS;
import VO.LivroVO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class IULivros extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form IULivros
     */
    public IULivros() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        LivroPERS livroPERS = new LivroPERS();
        List livros = livroPERS.retornarLivros();
        
        model = (DefaultTableModel) tabelaLivros.getModel(); 
        LivroVO livroVO;
        int i;
        int tam = livros.size();
        for(i=0; i<tam; i++){
            livroVO = (LivroVO) livros.get(i);       
            model.addRow(new String [] {livroVO.getCodigo(),livroVO.getTitulo(),livroVO.getISBN(),livroVO.getEditora(), livroVO.getLocalEdicao()});
        }   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        autores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "ISBN", "Editora", "Local de Edição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLivros);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Livros");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        autores.setText("Autores");
        autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterar)
                    .addComponent(excluir)
                    .addComponent(cadastrar)
                    .addComponent(voltar)
                    .addComponent(autores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
        new IUMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        this.dispose();
        new IUCadastrarLivro().setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresActionPerformed
        int linhaSelecionada = tabelaLivros.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        String codigoLivro = (String) model.getValueAt(linhaSelecionada, 0);
        String tituloLivro = (String) model.getValueAt(linhaSelecionada, 1);
        
        this.dispose();
        new IUExibirAutores(codigoLivro, tituloLivro).setVisible(true);
    }//GEN-LAST:event_autoresActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int linhaSelecionada = tabelaLivros.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        String codigoLivro = (String) model.getValueAt(linhaSelecionada, 0);
        
        LivroPERS livroPERS = new LivroPERS();
        String msg = livroPERS.excluirLivro(codigoLivro);
        
        JOptionPane.showMessageDialog(null, msg);
        this.dispose();
        new IULivros().setVisible(true);
    }//GEN-LAST:event_excluirActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
       int linhaSelecionada = tabelaLivros.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado");
            return;
        }
        
        LivroVO livroVO = new LivroVO();
        livroVO.setCodigo((String) model.getValueAt(linhaSelecionada, 0));
        livroVO.setTitulo((String) model.getValueAt(linhaSelecionada, 1));
        livroVO.setISBN((String) model.getValueAt(linhaSelecionada, 2));
        livroVO.setEditora((String) model.getValueAt(linhaSelecionada, 3));
        livroVO.setLocalEdicao((String) model.getValueAt(linhaSelecionada, 4));
        
        LivroPERS livroPERS = new LivroPERS();
        livroVO.setAutor((ArrayList<String>) livroPERS.retornarAutores(livroVO.getCodigo()));
        
        this.dispose();
        new IUAlterarLivro(livroVO).setVisible(true);
        
    }//GEN-LAST:event_alterarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton autores;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLivros;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
